# Generated by Django 3.2.23 on 2024-01-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0007_auto_20240106_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='chair_photo',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
